language: node_js
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_48fb3927a4e3_key -iv $encrypted_48fb3927a4e3_iv
-in llavehlc.enc -out llavehlc -d
- eval "$(ssh-agent -s)"
- chmod 600 ./llavehlc
- echo -e "Host 51.210.103.111\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./llavehlc
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
node_js:
-'14'
branches:
 only:
 - master
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"